---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: store-front-end
  namespace: socks-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: store-front-end
    spec:
      containers:
      - name: store-front-end
        image: amitmahajan/store-front-end:latest
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "false"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 30
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: store-front-end
  labels:
    name: store-front-end
  namespace: socks-store
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: store-front-end